services:
  my_authen_api:
    container_name: my_authen_api
    build: ./backend
    image: my_authen_api_image
    
    depends_on:
      - db

  db:
    container_name: postgres_db
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: lborjgldo_9384kkfgp
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  my_authen_web:
    container_name: my_authen_web
    build: ./frontend
    
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - my_authen_api

  nginx:
    image: nginx
    container_name: nginx_reverse_proxy
    ports:
      - "80:80" 
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - my_authen_web
      - my_authen_api

volumes:
  pgdata:
