version: '3'

services:
  my_authen_api:
    container_name: my_authen_api
    build: ./backend
    image: my_authen_api_image
    ports:
      - "30002:5000"
    
  db:
    container_name: postgres_db
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: lborjgldo_9384kkfgp
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
